---
 - name: This is the simple plat to understand debug module
   hosts: localhost
   tasks:
   - name: Printing a msg with msg parameter of debug module 1
     debug: msg="Welcome to Ansible Playbooks"
   - name: 
     debug: Printing a msg with msg parameter of debug module 2
        msg: "Welcome to Ansible Playbooks"
   - name: 
      debug: Printing a msg with msg parameter of debug module 3
        msg: 
          - "Welcome to Ansible Playbooks"
          - "These are basic concepts"
          - "We will do advanced as well"
          

# Run
# ansible-playbook "23-Print-any-message-using-playbook.yml"

