---
# vars file for roles/xyz_tomcat
 req_tomcat_ver: 9.0.41
 tomcat_url: http://mirrors.estointernet.in/apache/tomcat/tomcat-{{req_tomcat_ver.split('.')[0]}}/v{{req_tomcat_ver}}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz
 tomcat_port: 8090
